### ISSUE TITLE
List Can Be Added to AdAway on Android, but Nodes Won't Get Blocked

### ISSUE THREAD

**Issue by ryanbarillosofficial** [SecOps-Institute/Tor-IP-Addresses#12]
Hi. I tried converting the **.lst** file into a **.txt** file using a [Python script I made a few hours ago](https://github.com/ryanbarillos/dns-blocklists/blob/main/hosts/everyone/tor/nodes.py) with all the necessary redirects for use on [AdAway](https://f-droid.org/en/packages/org.adaway/). 

AdAway is a FOSS DNS manager on Android used primarily for ad-blocking, it can also be used to block any other websites.

While the script has no issues just by reading & running it, AdAway can't pick up on these Tor nodes and thus can't be blocked by the app. I'd like to know if this is something to do with the IP addresses on this repo, my script, or the Android app itself.

You may reproduce the results with the following:
- Install AdAway on an Android device
- Configure it to either use root or a VPN option
- Add my list for blocking using this link https://raw.githubusercontent.com/ryanbarillos/dns-blocklists/main/hosts/everyone/tor/nodes.txt

It should display "X Hosts", where X is the sum of all IP addresses blocked using the host source. However, that doesn't get displayed and thus none of the Tor nodes get blocked on my Android phone. And I'd like to know what could be causing it.

FYI I've already filed an [issue on the AdAway GitHub repo](https://github.com/AdAway/AdAway/issues/4042) to also find help from the app developers, too. Looking to find solutions from all sides.

Thanks in advance.

Screenshots of this unusual behavior:
![Screenshot_20240101-162733_AdAway](https://github.com/SecOps-Institute/Tor-IP-Addresses/assets/129530399/6d76e5f6-89f8-4907-b4f9-607f24d45d5b)
![Screenshot_20240101-162730_AdAway](https://github.com/SecOps-Institute/Tor-IP-Addresses/assets/129530399/80199a5c-76e1-4d9b-9ce2-6ad44928df13)

**Comment by aarvee11** [comment]
Unable to find any of the URLs active or repos as well. Closing as Obsolete.
