### ISSUE TITLE
tor-nodes.lst IS EMPTY

### ISSUE THREAD

**Issue by AcidSlide** [SecOps-Institute/Tor-IP-Addresses#13]
The current `tor-nodes.lst` is empty

**Comment by AcidSlide** [comment]
Related commit is: https://github.com/SecOps-Institute/Tor-IP-Addresses/commit/3dc7a5de0e71c329e07271124d30881c031c3e32

**Comment by aarvee11** [comment]
Apologies, We ran out of funds, and took a short break 

We target to resume by 29th Feb 2024. 

Thank you for the support, trust and patience.

**Comment by aarvee11** [comment]
Please check now. Still the lists are not getting updated hourly as done previously. Working on the same

**Comment by AcidSlide** [comment]
Thanks.. I'll check this as soon as I can
