### ISSUE TITLE
Hi, github TOR IP appears to be empty. Did a problem occur?

### ISSUE THREAD

**Issue by 101ping101** [SecOps-Institute/Tor-IP-Addresses#6]
https://github.com/SecOps-Institute/Tor-IP-Addresses/blob/master/tor-nodes.lst

**Comment by 101ping101** [comment]
CAn you added 109.70.100.19  TOR IP

**Comment by aarvee11** [comment]
Fixed !

**Comment by inyourpc** [comment]
what is port of these ips ?
