### ISSUE TITLE
The list has stopped being updated

### ISSUE THREAD

**Issue by daulbrecht** [SecOps-Institute/Tor-IP-Addresses#9]
The list has stopped being updated since March 24. Is everything ok?

**Comment by theFakeFrog** [comment]
sadly yes. i guess its the end for this page

**Comment by cybermonkee** [comment]
If you run this command - it will give you all the IP addresses for valid relays from their API. 

curl -s 'https://onionoo.torproject.org/summary?search=flag:valid' -o - | jq -cr '.relays[].a[0]' | sort

This command will give you a list of all the running relays from their API.
 curl -s 'https://onionoo.torproject.org/summary?search=flag:running' -o - | jq -cr '.relays[].a[0]' | sort

**Comment by daulbrecht** [comment]
@cybermonkee Thank you for getting back to me. In fact, I was previously only using the exit nodes list, but I found based on your answer that it is possible to get only these IPs changing the filter at the final of the call, this is all I need: https://onionoo.torproject.org/summary?search=flag:Exit

Thank you again.

**Comment by aarvee11** [comment]
Its fixed now ! Apologies for the inconvenience
